name: export slide

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - uses: actions/setup-node@v1.1.0
    - run: npm install @marp-team/marp-cli
    - run: marp slide-deck.md -o index.html
    - uses: ncipollo/release-action@v1
